### PR TITLE
GH-507: N4 meta-properties should be read-only

### PR DESCRIPTION
**Pull request by mor-n4**
See #507.

### CODE REVIEW

**Comment by mor-n4** [comment]
n.b. I chose to not implement "deep immutability" as part of this bug. If we want that, we should create a user story for improving the reflection in general and then add it there.

FYI: all interesting changes are in file `builtin_n4.n4ts`. The rest is just follow-up.

**Comment by mmews-n4** [comment]
Should I still review this?

**Comment by mor-n4** [comment]
tests green
PENDING: test with OPR

**Comment by mor-n4** [comment]
ok with OPR

**Pull request merged**
