### PR TITLE
GH-2147: As a developer I want open workspace symbol to be responsive

### PR DESCRIPTION
**Pull request by mor-n4**
See #2147.

### CODE REVIEW

**Comment by mor-n4** [comment]
NOTE: performance could be improved further by sending symbols to the client in serveral steps, but that would require a newer version of LSP, which would require an update of lsp4j + Xtext.

See
https://microsoft.github.io/language-server-protocol/specifications//specification-3-17/#progress
https://microsoft.github.io/language-server-protocol/specifications//specification-3-17/#partialResults

Once this is done, the better filtering logic can & should be activated, here:
https://github.com/eclipse/n4js/blob/5b9654de939883764ec6ec5d59f1a612618a00ee/plugins/org.eclipse.n4js.ide/src/org/eclipse/n4js/ide/server/symbol/N4JSDocumentSymbolService.java#L55-L61

**Comment by mor-n4** [comment]
PENDING: log a message if a partial result token is received from the client!

**Review by mmews-n4 — APPROVED** [review]
👍 Very nice!

**Comment by mor-n4** [comment]
Builds green, merging ...

**Pull request merged**
