### PR TITLE
GH-614: adding Headers.forEach, Buffer.from, NodeURL.query

### PR DESCRIPTION
**Pull request by dbo**
issue #614

@kduske-n4 please

### CODE REVIEW

**Comment by yoosiba** [comment]
@kduske-n4 this updates `n4js-libs` but not the `shipped-code` i.e. you will not see this change in IDE.
I expect to fail in https://github.com/eclipse/n4js/blob/master/tests/org.eclipse.n4js.external.libraries.update.tests/src/org/eclipse/n4js/external/libraries/update/tests/UpdateShippedCodeTest.java

In short, run https://github.com/eclipse/n4js/blob/master/plugins/org.eclipse.n4js.external.libraries.update/src/org/eclipse/n4js/external/libraries/update/UpdateShippedCode.mwe2 and update PR with the changes.

**Comment by kduske-n4** [comment]
@yoosiba have you already done it?

**Comment by yoosiba** [comment]
@dbo  @kduske-n4  there were some test failures, but they seemed unrelated. I will re-run them, then I will update you on this progress.

**Comment by yoosiba** [comment]
resolved test issues. merging.

**Pull request merged**
