### PR TITLE
GH-1027: Runtime project "n4js-runtime-html5" is missing its marker file

### PR DESCRIPTION
**Pull request by mor-n4**
See #1027.

No changes in other repo.

### CODE REVIEW

**Comment by lbeurerkellner** [comment]
Would be a good opportunity to generally fix https://github.com/eclipse/n4js/issues/1010

**Comment by mor-n4** [comment]
@lbeurerkellner yeah, I did check all projects.

**Comment by mor-n4** [comment]
Builds green.

**Comment by mor-n4** [comment]
Thanks, merging ...

**Pull request merged**
