### PR TITLE
GH-1225: Nightly build on Eclipse fails due to the lack of docker (used for Eclipse helper generation)

### PR DESCRIPTION
**Pull request by qtran-n4**
Task: https://github.com/eclipse/n4js/issues/1225

### CODE REVIEW

**Comment by torstenkraemer** [comment]
Hi @qtran-n4 ! I'm not sure what happens here or happened in the past - but the "dist" folder should not be checked in -  neither any large binaries like PDFs. 
This will generate commit-noise and bloat the repository quickly ...

**Comment by torstenkraemer** [comment]
@qtran-n4 but as far as I understand these HTML pages are generated in the build-process and not hand-written. So they should not be checked in.

**Comment by qtran-n4** [comment]
@torstenkraemer Good point. They have been there. I have deleted the `dist` and `src-gen` folders and let's wait for the build.

**Comment by qtran-n4** [comment]
Thanks! The build result looks fine. Merging...

**Pull request merged**
