### PR TITLE
GH-406: Move manually registered extensions into HeadlessExtensionRegistrationHelper

### PR DESCRIPTION
**Pull request by qtran-n4**
Task: https://github.com/eclipse/n4js/issues/406

### CODE REVIEW

**Comment by yoosiba** [comment]
try to move the `HeadlessTestDiscoveryTest` to the `org.eclipse.n4js.hlc.tests` bundle, and the `HeadlessExtensionRegistrationHelper.java` to the `org.eclipse.n4js.hlc`. Undo dependency changes in the `org.eclipse.n4js.generator.headless/META-INF/MANIFEST.MF`

**Comment by qtran-n4** [comment]
@yoosiba Moved `HeadlessExtensionRegistrationHelper` into a new bundle `org.eclipse.n4js.headless.helper` as discussed. All builds are green so merging.

**Comment by qtran-n4** [comment]
@mor-n4 I introduced a new bundle org.eclipse.n4js.headless.helper and put `HeadlessExtensionRegistrationHelper` in that bundle. Please check if this is OK.

**Comment by qtran-n4** [comment]
Thanks for your feedback!

**Pull request merged**
