### PR TITLE
Hyperlink DOIs against preferred resolver

### PR DESCRIPTION
**Pull request by katrinleinweber**
Repeat of #840 plus other minor link updates, using `commit -s` and an email address that accounts.eclipse.org accepts. cc @jpilgrim

### CODE REVIEW

**Comment by katrinleinweber** [comment]
This is not exactly advertisement for DCOs or CLAs :-/

**Comment by jpilgrim** [comment]
@katrinleinweber, I'm really sorry that we kept you waiting for so long. I have no idea why the ip-validation fails. I will ask the Eclipse guys for help.

**Comment by jpilgrim** [comment]
@katrinleinweber I added a comment to a similar bug in https://bugs.eclipse.org/bugs/show_bug.cgi?id=539831 -- let's see what we can learn from that.

**Comment by katrinleinweber** [comment]
Cool, thank you :-)

**Comment by jpilgrim** [comment]
Replaced by #1419

**Pull request closed without merging**
