### PR TITLE
GH-1293: Harden constraints for URIs - no empty segments

### PR DESCRIPTION
**Pull request by szarnekow**
[#1293] Harden constraints for URIs - no empty segments

### CODE REVIEW

**Comment by jpilgrim** [comment]
@szarnekow Is this PR ready to be merged, i.e., does it make sense to review it?

**Comment by szarnekow** [comment]
> @szarnekow Is this PR ready to be merged, i.e., does it make sense to review it?

I'm not sure about the existing tests - could be that there are some breakages with this hardened constraint. But yes, review comments are welcome, even though I'll find the time to continue on this only at the end of this month.

**Comment by szarnekow** [comment]
Roger that. Please go ahead with the merge.

**Comment by mmews-n4** [comment]
Still green... merging.

**Pull request merged**
