### PR TITLE
GH-234: NPE in find references 

### PR DESCRIPTION
**Pull request by qtran-n4**
== Task
Link: https://github.com/eclipse/n4js/issues/234

### CODE REVIEW

**Comment by qtran-n4** [comment]
@lbeurerkellner : Please review. Thanks!

**Comment by qtran-n4** [comment]
It is not possible to reproduce this bug, therefore no test :(

**Comment by lbeurerkellner** [comment]
As discussed the issue might a synchronisation issue with the OpenDocumentTracker and XtextDocument#disposeInput.

The fix looks good to me although I hope in the long run the workaround can be removed.

**Comment by qtran-n4** [comment]
@lbeurerkellner Thanks for the review! Build is green merging now.

**Pull request merged**
