### PR TITLE
GH-2012: As a smith I want to have a test suite for the n4jsd-generator

### PR DESCRIPTION
**Pull request by mor-n4**
See #2012.

### CODE REVIEW

**Comment by mor-n4** [comment]
@mmews-n4 If you want to test this on your machine, you can do:
```
cd n4js-tools/\@n4js-temp/n4jsd-generator/
npm install
npm run build
npm test
```

**Comment by mmews-n4** [comment]
Thanks

**Review by mmews-n4 — APPROVED** [review]
👍  Very nice test suite for all features. Good infrastructure to extend when added new features!

**Comment by mor-n4** [comment]
Thank you!

Builds green (also the generator publishing build). Merging ...

**Pull request merged**
