### PR TITLE
GH-2018: As a smith I want to remove new errors/warnings/infos of Eclipse 2020-12

### LINKED ISSUE #2018: As a smith I want to remove new errors/warnings/infos of Eclipse 2020-12
An update to Eclipse 2020-12 (from 2019-12) causes more than 30 new issues (1 error, several warnings and infos) to be shown in the Problems View.

AC
* reduce these issues as much as possible

### PR DESCRIPTION
**Pull request by mmews-n4**
closes #2018

### CODE REVIEW

**Comment by mmews-n4** [comment]
@mor-n4 When reviewing this, please also check how your installation of Eclipse handles these changes.

**Comment by mor-n4** [comment]
With these changes I get 35 warnings and 8 infos in the workspace.

**Comment by mmews-n4** [comment]
@mor-n4 Please have another look! Thanks!

**Review by mor-n4 — APPROVED** [review]
Thanks!

**Pull request merged**
