### PR TITLE
GH-1144: Upgrade n4js-node/node-fetch to 2.2.0

### PR DESCRIPTION
**Pull request by dbo**
#1144

@qtran-n4 please

### CODE REVIEW

**Comment by qtran-n4** [comment]
@dbo Don't forget to merge

**Comment by mor-n4** [comment]
Did you delete the `package-json.lock` on purpose? iirc the publishing script in the nightly will use npm, not yarn, so the newly created `yarn.lock` will be ignored...

**Comment by dbo** [comment]
I talked to @qtran-n4 about it, he mentioned yarn, so I deleted the package-lock.json.

**Comment by qtran-n4** [comment]
Yes, in `lerna.json` ( https://github.com/eclipse/n4js/blob/master/n4js-libs/lerna.json ), `yarn` is specified as `npmClient`

**Comment by mor-n4** [comment]
ok, thanks

**Pull request merged**
